using System.Text;
using System.Text.Json;

try
{
    var root = FindRepositoryRoot();
    using var catalog = JsonDocument.Parse(File.ReadAllBytes(Path.Combine(root, "generated", "operations.json")));
    var operations = catalog.RootElement.GetProperty("operations").EnumerateArray()
        .Select(value => value.GetProperty("operationId").GetString()!)
        .Order(StringComparer.Ordinal)
        .ToArray();

    var skillsByOperation = operations.ToDictionary(id => id, _ => new List<string>(), StringComparer.Ordinal);
    foreach (var manifestPath in Directory.EnumerateFiles(Path.Combine(root, "plugins"), "operations.json", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
    {
        var skill = Path.GetRelativePath(Path.Combine(root, "plugins"), Path.GetDirectoryName(manifestPath)!)
            .Replace('\\', '/');
        using var manifest = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        foreach (var value in manifest.RootElement.GetProperty("operationIds").EnumerateArray())
        {
            var operationId = value.GetString() ?? throw new InvalidDataException($"Operation IDs in '{manifestPath}' must be strings.");
            if (!skillsByOperation.TryGetValue(operationId, out var skills))
            {
                throw new InvalidDataException($"Skill '{skill}' references unknown operation '{operationId}'.");
            }
            skills.Add(skill);
        }
    }

    var covered = skillsByOperation.Count(pair => pair.Value.Count > 0);
    var output = new
    {
        operationCount = operations.Length,
        coveredOperationCount = covered,
        uncoveredOperationCount = operations.Length - covered,
        coveragePercent = operations.Length == 0 ? 100 : Math.Round(covered * 100m / operations.Length, 2),
        operations = skillsByOperation.Select(pair => new { operationId = pair.Key, skills = pair.Value.Order(StringComparer.Ordinal).ToArray() })
    };

    var jsonOptions = new JsonSerializerOptions { WriteIndented = true };
    File.WriteAllText(Path.Combine(root, "generated", "operation-coverage.json"), JsonSerializer.Serialize(output, jsonOptions) + Environment.NewLine);

    var markdown = new StringBuilder()
        .AppendLine("# Agent Gateway API coverage")
        .AppendLine()
        .AppendLine("This file is generated by `dotnet run --project tools/generate-coverage`. Do not edit it manually.")
        .AppendLine()
        .AppendLine($"**Coverage: {covered} of {operations.Length} operations ({output.coveragePercent:0.##}%).**")
        .AppendLine()
        .AppendLine("| Operation | Capability skill(s) |")
        .AppendLine("| --- | --- |");
    foreach (var (operationId, skills) in skillsByOperation)
    {
        markdown.Append("| `").Append(operationId).Append("` | ")
            .Append(skills.Count == 0 ? "—" : string.Join(", ", skills.Select(skill => $"`{skill}`")))
            .AppendLine(" |");
    }
    File.WriteAllText(Path.Combine(root, "docs", "api-coverage.md"), markdown.ToString());

    Console.WriteLine($"Agent Gateway API coverage: {covered} of {operations.Length} operations ({output.coveragePercent:0.##}%).");
    if (covered != operations.Length)
    {
        foreach (var operation in skillsByOperation.Where(pair => pair.Value.Count == 0).Select(pair => pair.Key))
            Console.Error.WriteLine($"Uncovered operation: {operation}");
        return 1;
    }
    return 0;
}
catch (Exception exception)
{
    Console.Error.WriteLine($"Coverage generation failed: {exception.Message}");
    return 1;
}

static string FindRepositoryRoot()
{
    foreach (var startingPath in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
    {
        for (var directory = new DirectoryInfo(startingPath); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "generated", "operations.json")))
                return directory.FullName;
        }
    }
    throw new DirectoryNotFoundException("Could not locate the repository root containing generated/operations.json.");
}
